kind: Pod
apiVersion: v1
metadata:
  name: build-pod
spec:
  containers:
    - name: php
      image: php:7
      tty: true
      command:
        - cat
    - name: docker
      image: docker:latest
      tty: true
      command:
        - cat
      volumeMounts:
        - name: dockersocket
          path: /var/lib/docker.sock
  volumes:
    - name: dockersocket
      hostPath:
        path: /var/lib/docker.sock
