kind: Pod
apiVersion: v1
metadata:
  name: build-pod
spec:
  serviceAccount: jenkins
  containers:
    - name: php
      image: php:7
      tty: true
      command:
        - cat
    - name: docker
      image: docker:latest
      tty: true
      command:
        - cat
      securityContext:
        privileged: true
      volumeMounts:
        - name: dockersocket
          mountPath: /var/run/docker.sock
        - name: nexuslogin
          mountPath: /root/.docker
  volumes:
    - name: dockersocket
      hostPath:
        path: /var/run/docker.sock
    - name: nexuslogin
      configMap:
        name: nexus-login
